<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net471</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>GunsAreLoud.Tests</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\client\GunsAreLoud.Client\GunsAreLoud.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>$(SptGameDir)\BepInEx\core\BepInEx.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(SptGameDir)\BepInEx\core\0Harmony.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(SptGameDir)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(SptGameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(SptGameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SptGameDir)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
