<Project>
  <PropertyGroup>
    <GunsAreLoudVersion>1.0.0</GunsAreLoudVersion>
    <Version>$(GunsAreLoudVersion)</Version>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <SptGameDir Condition="'$(SptGameDir)' == ''">D:\Games\SPT_4.1.5</SptGameDir>
  </PropertyGroup>
</Project>
