// Generated by docs/reference/headphones/build_runtime_profiles.py; edit selection/source records.
using System.Collections.Generic;
namespace GunsAreLoud.Client.Runtime
{
    internal static partial class HeadsetProfileRegistry
    {
        private static void ApplyReferenceProfiles(Dictionary<string, HeadsetProfile> profiles)
        {
            ReplaceReference(profiles, "tactical-sport-proposed", "sporttac-family-reference",
                "MT16H210F headband", "SportTac family transfer; exact Tactical Sport SKU unverified",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f, 8000.0f },
                    new[] { 12.1f, 17.9f, 27.0f, 26.8f, 30.5f, 38.3f, 36.4f }, new[] { 4.3f, 3.1f, 3.8f, 3.0f, 3.0f, 3.7f, 5.4f },
                    "EN 352", "https://multimedia.3m.com/mws/media/940033O/fp3584-sporttac-pdf.pdf?fn=FP3584_SportTac.pdf", "1", HeadsetEvidence.FamilySurrogate, new[] { 7.8f, 14.8f, 23.2f, 23.8f, 27.5f, 34.6f, 31.0f }));
            ReplaceReference(profiles, "comtac-iv-proposed", "comtac-iv-ultrafit-reference",
                "PELTIP4-01 UltraFit", "UltraFit selected; game tip not independently identified; no Torque substitution",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f, 8000.0f },
                    new[] { 28.6f, 27.0f, 30.3f, 29.2f, 30.9f, 31.6f, 32.0f }, new[] { 5.3f, 6.0f, 6.0f, 5.4f, 3.4f, 6.6f, 4.5f },
                    "EN 352", "https://multimedia.3m.com/mws/media/1142194O/3m-peltor-comtac-iv-headset-datasheet-pdf.pdf", "", HeadsetEvidence.FamilySurrogate, new[] { 23.3f, 21.0f, 24.4f, 23.8f, 27.4f, 25.1f, 27.6f }));
            ReplaceReference(profiles, "comtac-v-proposed", "comtac-v-foam-reference",
                "MT20H682 folding headband foam", "Standard foam headband selected; no helmet or gel correction",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 3150.0f, 4000.0f, 6300.0f, 8000.0f },
                    new[] { 13.6f, 17.7f, 28.8f, 31.9f, 32.3f, 39.3f, 39.9f, 42.1f, 41.4f }, null,
                    "ANSI S3.19", "https://www.manualslib.com/manual/2180471/3m-Peltor-Comtac-V.html?page=4", "4", HeadsetEvidence.Measured, null));
            ReplaceReference(profiles, "comtac-vi-proposed", "comtac-vi-foam-reference",
                "MT20H682FB NIB foam headband", "Standard foam headband selected; no gel or dual protection",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f, 8000.0f },
                    new[] { 11.6f, 17.6f, 30.5f, 29.7f, 29.4f, 32.8f, 38.3f }, new[] { 2.3f, 2.1f, 2.9f, 2.3f, 3.2f, 2.1f, 4.8f },
                    "EN 352", "https://multimedia.3m.com/mws/media/2410397O/3m-defence-and-public-safety-catalogue-emea-english.pdf", "30", HeadsetEvidence.Measured, new[] { 9.3f, 15.5f, 27.6f, 27.4f, 26.2f, 30.7f, 33.5f }));
            ReplaceReference(profiles, "tep-300-proposed", "tep-300-ultrafit-reference",
                "EU UltraFit", "UltraFit selected as conservative documented tip; game tip unspecified",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f, 8000.0f },
                    new[] { 32.8f, 30.2f, 31.6f, 31.2f, 33.0f, 34.4f, 37.9f }, new[] { 6.2f, 4.5f, 5.4f, 4.4f, 4.0f, 4.8f, 3.9f },
                    "EN 352-2:2020", "https://multimedia.3m.com/mws/media/1854243O/3m-peltor-techn-datasheet-tep-300-eu.pdf?fn=DS17043_TEP_300_EU.pdf", "2", HeadsetEvidence.FamilySurrogate, new[] { 26.6f, 25.7f, 26.2f, 26.8f, 29.0f, 29.6f, 34.0f }));
            ReplaceReference(profiles, "razor-proposed", "razor-digital-bt-family-reference",
                "GWP-DRQBT Digital BT", "Digital BT family transfer; exact game Digital SKU unverified; missing 8 kHz SD remains unknown",
                new HeadsetPassiveProfile(new[] { 125.0f, 250.0f, 500.0f, 1000.0f, 2000.0f, 3150.0f, 4000.0f, 6300.0f, 8000.0f },
                    new[] { 17.1f, 17.7f, 23.4f, 28.2f, 32.2f, 37.2f, 37.9f, 40.2f, 38.5f }, new[] { 3.3f, 2.3f, 2.5f, 1.4f, 2.6f, 3.9f, 3.8f, 3.8f, float.NaN },
                    "ANSI S3.19-1974", "https://manuals.plus/m/4bb12ba42f53510d01bc4c0b1b9c17185b6b4a8e99315e6a0eb70f248dd87582", "1", HeadsetEvidence.FamilySurrogate, null));
        }
        private static void ReplaceReference(Dictionary<string, HeadsetProfile> profiles, string previousId,
            string id, string configuration, string assumption, HeadsetPassiveProfile passive)
        {
            HeadsetProfile previous = null;
            foreach (var profile in profiles.Values)
                if (profile.ProfileId == previousId) { previous = profile; break; }
            if (previous == null) throw new System.InvalidOperationException("Missing reference target: " + previousId);
            var ids = new string[previous.TemplateIdCount];
            for (int i = 0; i < ids.Length; i++) ids[i] = previous.TemplateIdAt(i);
            var assumptions = new string[previous.AssumptionCount + 1];
            for (int i = 0; i < previous.AssumptionCount; i++) assumptions[i] = previous.AssumptionAt(i);
            assumptions[assumptions.Length - 1] = assumption;
            var missing = new string[previous.MissingDataCount];
            for (int i = 0; i < missing.Length; i++) missing[i] = previous.MissingDataAt(i);
            var replacement = new HeadsetProfile(id, ids, previous.PhysicalFamily, configuration,
                previous.Mounting, configuration, passive, previous.Electronics, missing, assumptions);
            foreach (string templateId in ids) profiles[templateId] = replacement;
        }
    }
}
