"""Generate selected runtime curves from reviewed research; --check detects drift."""
import json
import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent
TARGET = ROOT.parents[2] / 'client/GunsAreLoud.Client/Runtime/HeadsetReferenceProfiles.cs'
def quoted(value):
    return json.dumps(value, ensure_ascii=False)
def array(values):
    if values is None:
        return 'null'
    return 'new[] { ' + ', '.join('float.NaN' if v is None else str(float(v)) + 'f' for v in values) + ' }'
selection = json.loads((ROOT / 'calculation-selection.json').read_text())
lines = ['// Generated by docs/reference/headphones/build_runtime_profiles.py; edit selection/source records.',
'using System.Collections.Generic;', 'namespace GunsAreLoud.Client.Runtime', '{',
'    internal static partial class HeadsetProfileRegistry', '    {',
'        private static void ApplyReferenceProfiles(Dictionary<string, HeadsetProfile> profiles)', '        {']
for row in selection['profiles']:
    data = json.loads((ROOT / row['researchFile']).read_text(encoding='utf-8-sig'))
    for token in row['jsonPointer'].strip('/').split('/'):
        data = data[int(token)] if isinstance(data, list) else data[token]
    freq = data.get('frequencies_hz', data.get('frequenciesHz'))
    mean = data.get('mean_db', data.get('meanDb'))
    sd = data.get('sd_db', data.get('sdDb'))
    apv = data.get('apv_db', data.get('apvDb'))
    assert len(freq) == len(mean) and 1 <= len(freq) <= 9
    assert all(a < b for a, b in zip(freq, freq[1:]))
    lines += ['            ReplaceReference(profiles, '+quoted(row['replaces'])+', '+quoted(row['profileId'])+',',
              '                '+quoted(row['configuration'])+', '+quoted(row['assumption'])+',',
              '                new HeadsetPassiveProfile('+array(freq)+',',
              '                    '+array(mean)+', '+array(sd)+',',
              '                    '+quoted(row['standard'])+', '+quoted(row['source'])+', '+quoted(row['page'])+', HeadsetEvidence.'+row['evidence']+', '+array(apv)+'));']
lines += ['        }', '''        private static void ReplaceReference(Dictionary<string, HeadsetProfile> profiles, string previousId,
            string id, string configuration, string assumption, HeadsetPassiveProfile passive)
        {
            HeadsetProfile previous = null;
            foreach (var profile in profiles.Values)
                if (profile.ProfileId == previousId) { previous = profile; break; }
            if (previous == null) throw new System.InvalidOperationException("Missing reference target: " + previousId);
            var ids = new string[previous.TemplateIdCount];
            for (int i = 0; i < ids.Length; i++) ids[i] = previous.TemplateIdAt(i);
            var assumptions = new string[previous.AssumptionCount + 1];
            for (int i = 0; i < previous.AssumptionCount; i++) assumptions[i] = previous.AssumptionAt(i);
            assumptions[assumptions.Length - 1] = assumption;
            var missing = new string[previous.MissingDataCount];
            for (int i = 0; i < missing.Length; i++) missing[i] = previous.MissingDataAt(i);
            var replacement = new HeadsetProfile(id, ids, previous.PhysicalFamily, configuration,
                previous.Mounting, configuration, passive, previous.Electronics, missing, assumptions);
            foreach (string templateId in ids) profiles[templateId] = replacement;
        }''', '    }', '}']
output = '\n'.join(lines) + '\n'
if '--check' in sys.argv:
    assert TARGET.read_text(encoding='utf-8-sig') == output, 'Generated runtime profiles are stale'
else:
    TARGET.write_text(output, encoding='utf-8-sig')
print('Verified 6 selected reference curves' if '--check' in sys.argv else 'Generated 6 selected reference curves')
